/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyserResult: typeof import('./../components/AnalyserResult.vue')['default']
    DialogWrapper: typeof import('./../components/DialogWrapper.vue')['default']
    FrequencyRatio: typeof import('./../components/chart/FrequencyRatio.vue')['default']
    NoticeDialog: typeof import('./../components/NoticeDialog.vue')['default']
    OriginalAudio: typeof import('./../components/chart/OriginalAudio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
